import calorie_counter_with_classes as ccc
# dct = ccc.DailyCalorieTracker(date="Aug20",current_weight=73)
# dct.add_meal_for_the_day('breakfast','rava upma',1)
# dct.add_meal_for_the_day('snack','pitted date',1,ismeal=False)
# dct.add_meal_for_the_day('smoothie','apple smoothie',1)
# dct.add_meal_for_the_day('snack','black coffee',1)
# dct.add_meal_for_the_day('snack','digestive lite',1)
# dct.add_meal_for_the_day('lunch','methi thepla',3)
# dct.add_meal_for_the_day('lunch','mango pickle',1)
# dct.add_meal_for_the_day('lunch','dahi',0.5)
# dct.add_meal_for_the_day('snack','mocha',1)
# dct.add_meal_for_the_day('dinner','methi thepla',1.5)
# dct.add_meal_for_the_day('dinner','mixed veg raita',1)
# dct.add_meal_for_the_day('snack','marie biscuit',1)
# dct.print_calorie_data(152)

# dct = ccc.DailyCalorieTracker(date="Aug21",current_weight=73)
# dct.add_meal_for_the_day('breakfast','homemade poha',1)
# dct.add_meal_for_the_day('snack','black coffee',1)
# dct.add_meal_for_the_day('lunch','pizza sandwich',1)
# dct.add_meal_for_the_day('snack','mocha',1)
# dct.add_meal_for_the_day('snack','date moon cake',0.5,ismeal=False)
# dct.add_meal_for_the_day('snack','cookies and cream mousse cup',0.5,ismeal=False)
# dct.add_meal_for_the_day('snack','pappad small',0.5,ismeal=False)
# dct.add_meal_for_the_day('snack','harvest snap',1,ismeal=False)
# dct.add_meal_for_the_day('dinner','top ramen masala noodles',1.5,ismeal=False)
# dct.print_calorie_data(150)

# dct = ccc.DailyCalorieTracker(date="Aug22",current_weight=73)
# dct.add_meal_for_the_day('breakfast','quinoa dosa',3)
# dct.add_meal_for_the_day('breakfast','pumpkin chutney',1)
# dct.add_meal_for_the_day('snack','black coffee',1)
# dct.add_meal_for_the_day('smoothie','apple spinach smoothie',1)
# dct.add_meal_for_the_day('lunch','kala chana sabji',0.7)
# dct.add_meal_for_the_day('lunch','bajra roti',2)
# dct.add_meal_for_the_day('lunch','bhindi fry',0.4)
# dct.add_meal_for_the_day('snack','mocha',1)
# dct.add_meal_for_the_day('snack','digestive lite',1,ismeal=False)
# dct.add_meal_for_the_day('snack','pitted date',2,ismeal=False)
# dct.add_meal_for_the_day('snack','chawanprash',1,ismeal=False)
# dct.add_meal_for_the_day('salad','black bean spring mix salad',0.5)
# dct.add_meal_for_the_day('dinner','lemon millset',1)
# dct.print_calorie_data(350)

# dct = ccc.DailyCalorieTracker(date="Aug23",current_weight=73)
# dct.add_meal_for_the_day('snack','mixed nuts',1.5)
# dct.add_meal_for_the_day('breakfast','avocado egg sandwich',1)
# dct.add_meal_for_the_day('snack','nectarine',0.85,ismeal=False)
# dct.add_meal_for_the_day('snack','peach',0.4,ismeal=False)
# dct.add_meal_for_the_day('lunch','kala chana sabji',0.3)
# dct.add_meal_for_the_day('lunch','frozen roti',1)
# dct.add_meal_for_the_day('lunch','bhindi fry',0.6)
# dct.add_meal_for_the_day('lunch','quinoa dosa',1)
# dct.add_meal_for_the_day('lunch','pumpkin chutney',0.33)
# dct.add_meal_for_the_day('snack','mocha',1)
# dct.add_meal_for_the_day('salad','oat khakra chaat',1)
# dct.add_meal_for_the_day('dinner','generic chana dal wada',1)
# dct.add_meal_for_the_day('dinner','generic peanut chutney',6,ismeal=False)
# dct.add_meal_for_the_day('dinner','generic quick upma',1)
# dct.add_meal_for_the_day('dinner','generic mini veg uttapam',1.5)
# dct.add_meal_for_the_day('dinner','generic samosa chaat',1)
# dct.add_meal_for_the_day('dinner','jackfruit',1)
# dct.add_meal_for_the_day('dinner','generic sweet boondi',0.5)
# dct.print_calorie_data(642)

# dct = ccc.DailyCalorieTracker(date="Aug24",current_weight=71.7)
# dct.add_meal_for_the_day('snack','mixed nuts',1.5)
# dct.add_meal_for_the_day('breakfast','quinoa rice flour dosa',2)
# dct.add_meal_for_the_day('breakfast','pumpkin chutney',1)
# dct.add_meal_for_the_day('snack','black coffee',1)
# dct.add_meal_for_the_day('snack','pitted date',3)
# dct.add_meal_for_the_day('snack','buttermilk',1)
# dct.add_meal_for_the_day('snack','sweet boondi',3)
# dct.add_meal_for_the_day('lunch','top ramen',1.25)
# dct.add_meal_for_the_day('snack','mocha',1)
# dct.add_meal_for_the_day('snack','harvest snaps',1)
# dct.add_meal_for_the_day('snack','tandoori makhana',1,ismeal=False)
# dct.add_meal_for_the_day('snack','digestive',1,ismeal=False)
# dct.add_meal_for_the_day('snack','heart healthy nuts pack',0.25,ismeal=False)
# dct.add_meal_for_the_day('dinner','moong dal khichdi',1)
# dct.add_meal_for_the_day('snack','marie',1)
# dct.print_calorie_data(197)

# dct = ccc.DailyCalorieTracker(date="Aug25",current_weight=71.5)
# dct.add_meal_for_the_day('snack','mixed nuts',1.5)
# dct.add_meal_for_the_day('breakfast','homemade poha',1)
# dct.add_meal_for_the_day('smoothie','blueberry banana smoothie',1)
# dct.add_meal_for_the_day('snack','black coffee',1)
# dct.add_meal_for_the_day('lunch','multigrain roti',1.8)
# dct.add_meal_for_the_day('lunch','chana masala sabji',0.8)
# dct.add_meal_for_the_day('lunch','beans sabji',0.7)
# dct.add_meal_for_the_day('snack','mocha',1)
# dct.add_meal_for_the_day('salad','mini bell pepper salad',1)
# dct.add_meal_for_the_day('snack','tandoori makhana',1)
# dct.add_meal_for_the_day('snack','marie',3)
# dct.add_meal_for_the_day('snack','pitted date',1)
# dct.add_meal_for_the_day('lunch','lemon millet',1)
# dct.print_calorie_data(352)

# dct = ccc.DailyCalorieTracker(date="Aug26",current_weight=71.2)
# dct.add_meal_for_the_day('snack','mixed nuts',1.5)
# dct.add_meal_for_the_day('breakfast','avocado egg sandwich',1)
# dct.add_meal_for_the_day('snack','black coffee',1)
# dct.add_meal_for_the_day('smoothie','green apple pear orange smoothie',1)
# dct.add_meal_for_the_day('lunch','multigrain roti',1.8)
# dct.add_meal_for_the_day('lunch','chana masala sabji',0.2)
# dct.add_meal_for_the_day('lunch','beans sabji',0.3)
# dct.add_meal_for_the_day('lunch','cashew mushroom makhana curry',0.5)
# dct.add_meal_for_the_day('snack','mocha',1)
# dct.add_meal_for_the_day('snack','diet bhel chaat',1)
# dct.add_meal_for_the_day('snack','marie',2)
# dct.add_meal_for_the_day('dinner','masoor dal palak khichdi',1)
# dct.print_calorie_data(708)

# dct = ccc.DailyCalorieTracker(date="Aug27",current_weight=71.2)
# dct.add_meal_for_the_day('snack','mixed nuts',1.5)
# dct.add_meal_for_the_day('breakfast','rava upma',1)
# dct.add_meal_for_the_day('snack','black coffee',1)
# dct.add_meal_for_the_day('smoothie','apple spinach flaxseed smoothie',1)
# dct.add_meal_for_the_day('lunch','multigrain roti',1.8)
# dct.add_meal_for_the_day('lunch','achari baingan',1)
# dct.add_meal_for_the_day('lunch','drumstick sambar',1)
# dct.add_meal_for_the_day('snack','mocha',1)
# dct.add_meal_for_the_day('snack','rasmalai cake slice',0.5,ismeal=False)
# dct.add_meal_for_the_day('snack','dairy milk wholenut bar',0.67,ismeal=False)
# dct.add_meal_for_the_day('dinner','maggie masala noodles',1.25,ismeal=False)
# dct.print_calorie_data(600)

# dct = ccc.DailyCalorieTracker(date="Aug28",current_weight=71.2)
# dct.add_meal_for_the_day('breakfast','kellogs',1)
# dct.add_meal_for_the_day('snack','black coffee',1)
# dct.add_meal_for_the_day('lunch','restaurant laccha paratha',0.75,ismeal=False)
# dct.add_meal_for_the_day('lunch','restaurant dal tadka',0.25,ismeal=False)
# dct.add_meal_for_the_day('lunch','restaurant bhindi fry',0.25,ismeal=False)
# dct.add_meal_for_the_day('lunch','restaurant paneer butter masala',0.25,ismeal=False)
# dct.add_meal_for_the_day('lunch','restaurant veg biryani',0.25,ismeal=False)
# dct.add_meal_for_the_day('lunch','restaurant veg raita',0.25,ismeal=False)
# dct.add_meal_for_the_day('snack','baklava piece',0.5,ismeal=False)
# dct.add_meal_for_the_day('snack','jalebi',1,ismeal=False)
# dct.add_meal_for_the_day('snack','restaurant sweet pongal',0.125,ismeal=False)
# dct.add_meal_for_the_day('snack','harvest snap',1)
# dct.add_meal_for_the_day('dinner','rice flour and sooji dosa',3)
# dct.add_meal_for_the_day('dinner','idli podi',2)
# dct.add_meal_for_the_day('dinner','olive oil',0.5)
# dct.print_calorie_data(435)
